name: my_workflow
on: 
  pull_request:
    - paths: '**.js'
jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g es-check
      - run: es-check es5 './js/**/*.js'
