name: my_workflow
on: 
  pull_request:
    paths:
      '**.js'
jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install es-check
        run: npm install -g es-check

      - name: Run
        run: es-check es5 './js/**/*.js'
